version: '2'
services:
  postgres:
  #  restart: always
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/postgres/data:/var/lib/postgresql"
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: mic
      POSTGRES_PASSWORD: mic
      POSTGRES_DB: mic
    tty: true
    
  minionworker: 
    image: minion_build
    command: /data/worker.pl
    volumes:
      - $PWD/minion/data:/data
    environment:
      CONNECTION_STRING: 'postgresql://mic:mic@kiels-laptop/mic'
      NUMBER_OF_JOBS: 12
    depends_on:
      - postgres
    tty: true
